# CSCI 1360 - Assignment 5
## Question 1

- Total points 50

### Part A (Data Preprocessing), 50 points

[athens_airbnb.csv](athens_airbnb.csv) is an Airbnb listings dataset for properties in Athens, Greece. The features in the dataset contain property information, such as the number of bedrooms or the host rating. Each listing is assigned a binary label that indicates whether the property had a cancelled booking previously or not. The original dataset was downloaded from [Kaggle](https://www.kaggle.com/datasets/thedevastator/airbnb-prices-in-european-cities), whereas this version was modified for this assignment. The modified version suffers from several issues, such as missing values and imbalanced labels. Prepare this dataset for machine learning model training following these requirements:

- For missing values, use the `mode` value in the same column for imputation.
- Only encode the categorical features.
- Standardize features by removing the mean and scaling to unit variance.
- Randomly oversample the dataset to solve the imbalanced labels problem.
- Only allowed package imports: `sklearn`, `numpy`, `pandas`, and `random`.
- All functions in the allowed packages are allowed for usage in your solution.
- You are encouraged to read the documentation of each function you use in your solution.

[athens_airbnb_preprocessed.csv](athens_airbnb_preprocessed.csv) is the dataset file after applying the above preprocessing steps, you can view its content to check your solution.

#### Grading Rubric
- Correct file loading
- Correct imputation
- Correct categorical features encoding
- Correct scaling
- Correct oversampling

In [1]:
import pandas as pd

import numpy as np

df = pd.read_csv('athens_airbnb.csv')

# del df['listing_date']

# df.to_csv('athens_weekends.csv', index=False)

df

# arr = np.loadtxt('athens_weekends.csv',delimiter=',',skiprows=0)

,id,price,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,canceled
0,1,42.884259,Private room,False,True,3,False,0,1,9,93,1.0,1.553472,1
1,2,42.884259,Private room,False,True,3,False,0,1,10,90,1.0,0.953017,1
2,3,42.884259,Private room,False,True,3,False,0,1,9,78,1.0,0.953022,1
3,4,45.227662,Private room,False,True,2,True,0,1,10,97,1.0,2.491444,0
4,5,45.227662,Private room,False,True,2,True,0,1,10,96,1.0,2.491445,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,2623,649.122396,Entire home/apt,False,False,5,False,1,0,10,100,3.0,0.728336,1
2623,2624,684.273428,Entire home/apt,False,False,4,True,0,1,10,100,1.0,1.221746,1
2624,2625,707.004429,Entire home/apt,False,False,6,False,0,1,10,100,2.0,0.778499,1
2625,2626,869.167858,Entire home/apt,False,False,6,False,0,1,9,80,4.0,0.423140,1
2626,2627,1043.282638,Entire home/apt,False,False,6,True,1,0,10,100,3.0,0.629669,1

In [2]:
from sklearn.impute import SimpleImputer
np_arr = df.to_numpy()
imputer = SimpleImputer(strategy='most_frequent')
np_arr = imputer.fit_transform(np_arr)
# df
# df.to_csv('athens_weekends.csv', index=False)

# np_arr[np_arr > 5]
np_arr[139]

array([140, 115.9984065, 'Entire home/apt ', 'False       ',
       'False        ', 2, 'False             ', 1, 0, 10, 88, 1.0,
       2.739248105, 1], dtype=object)

In [3]:
from sklearn import preprocessing

encoder = preprocessing.OrdinalEncoder()

np_arr[:, 2] = encoder.fit_transform([np_arr[:, 2]])
np_arr[:, 3] = encoder.fit_transform([np_arr[:, 3]])
np_arr[:, 4] = encoder.fit_transform([np_arr[:, 4]])
np_arr[:, 6] = encoder.fit_transform([np_arr[:, 6]])

np_arr[139]

# np_arr[:, 2]

array([140, 115.9984065, 0.0, 0.0, 0.0, 2, 0.0, 1, 0, 10, 88, 1.0,
       2.739248105, 1], dtype=object)

In [4]:
# Standardize features

X = np_arr[:, 1:-1]

y = np_arr[:, -1]

print(X.shape)
print(y.shape)


X = preprocessing.StandardScaler().fit_transform(X)

# print(np_arr.shape)
# print(X.shape)
# y.shape
print(X[139])
print(y[139])

(2627, 12)
(2627,)
[-0.39527284  0.          0.          0.         -1.31680242  0.
  1.68209574 -0.7858822   0.43362644 -0.81970997 -0.40874962  0.9591406 ]
1

In [5]:
print(len(y[y  == 1]))
print(len(y[y  == 0]))

2419
208

In [6]:
import random
items_to_add = len(y[y  == 1]) - len(y[y  == 0])
indices_of_minor_label = np.where(y == 0)[0]
for i in range(items_to_add):
    # select an item randomly
    random_id = random.randint(0, len(indices_of_minor_label) - 1)
    # print(indices_of_minor_label[random_id])
    X = np.append(X, [X[ indices_of_minor_label[random_id] ]], axis=0)
    y = np.append(y, y[ indices_of_minor_label[random_id] ])
    # print(y[ indices_of_minor_label[random_id] ])

# indices_of_minor_label
print(len(y[y  == 1]))
print(len(y[y  == 0]))

2419
2419

In [7]:
print(X.shape)
print(y.shape)

y2 = np.reshape(y, (y.shape[0], 1))

print(y2.shape)

xy = np.append(X, y2, 1)
print(xy.shape)

np.savetxt("athens_airbnb_preprocessed.csv", xy, delimiter=",")

(4838, 12)
(4838,)
(4838, 1)
(4838, 13)